import type { TemplateItem } from "./types"

export const officeTemplate = {
  name: "Small Office",
  slug: "small-office",
  sector: "office",
  items: [
    {
      title: "Check walkways and exits are clear",
      description: "Ensure all corridors, doorways, and fire exits are free from obstructions.",
      category: "fire-safety",
      frequency: "daily",
      evidenceRequired: true,
      notesHint: "Note any obstructions found and actions taken",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/toolkit/offices/checklist.htm",
      sortOrder: 1,
    },
    {
      title: "Check first aid box is stocked",
      description: "Verify first aid kit contents are complete and within expiry dates.",
      category: "first-aid",
      frequency: "monthly",
      evidenceRequired: true,
      notesHint: "List any items replaced or added",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/firstaid/legislation.htm",
      sortOrder: 2,
    },
    {
      title: "Check fire extinguisher access is unobstructed",
      description: "Ensure fire extinguishers are in their designated spots with clear access.",
      category: "fire-safety",
      frequency: "monthly",
      evidenceRequired: true,
      notesHint: "Note extinguisher locations checked",
      sourceLabel: "GOV.UK",
      sourceUrl: "https://www.gov.uk/workplace-fire-safety-your-responsibilities",
      sortOrder: 3,
    },
    {
      title: "Review accident book presence",
      description: "Confirm accident book or digital equivalent is available and up to date.",
      category: "record-review",
      frequency: "monthly",
      evidenceRequired: false,
      notesHint: "Check recent entries are complete",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/riddor/reporting.htm",
      sortOrder: 4,
    },
    {
      title: "Check workstation area is tidy and cables are safe",
      description: "Verify desks, walkways, and cable management are tidy and trip-free.",
      category: "housekeeping",
      frequency: "weekly",
      evidenceRequired: false,
      notesHint: "Note any trailing cables or cluttered areas",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/msd/dse/guidance.htm",
      sortOrder: 5,
    },
    {
      title: "Review risk assessment",
      description: "Review the current risk assessment and update if circumstances have changed.",
      category: "record-review",
      frequency: "annual",
      evidenceRequired: true,
      notesHint: "Note any changes to premises, staff, or activities",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/simple-health-safety/risk-assessment.htm",
      sortOrder: 6,
    },
    {
      title: "Check emergency lighting test",
      description: "Verify emergency lighting is functioning by testing the system.",
      category: "fire-safety",
      frequency: "monthly",
      evidenceRequired: true,
      notesHint: "Record any failed units and actions taken",
      sourceLabel: "GOV.UK",
      sourceUrl: "https://www.gov.uk/workplace-fire-safety-your-responsibilities",
      sortOrder: 7,
    },
    {
      title: "Inspect electrical equipment (PAT visual check)",
      description: "Visually check portable electrical equipment for damage to plugs, cables, and casings.",
      category: "equipment",
      frequency: "monthly",
      evidenceRequired: false,
      notesHint: "Note any damaged items taken out of use",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/electricity/faq-portable-appliance-testing.htm",
      sortOrder: 8,
    },
  ],
}
