import type { TemplateItem } from "./types"

export const retailTemplate = {
  name: "Retail",
  slug: "retail",
  sector: "retail",
  items: [
    {
      title: "Check customer walkways are free from trip hazards",
      description: "Ensure all customer areas including aisles and entrance are clear of obstacles.",
      category: "slips-trips",
      frequency: "daily",
      evidenceRequired: false,
      notesHint: "Note any merchandise or packaging in walkways",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/slips/",
      sortOrder: 1,
    },
    {
      title: "Check stockroom access is clear",
      description: "Verify stockroom aisles, emergency exits, and fire extinguisher access are unobstructed.",
      category: "housekeeping",
      frequency: "daily",
      evidenceRequired: true,
      notesHint: "Note any stock blocking routes",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/toolkit/retail/checklist.htm",
      sortOrder: 2,
    },
    {
      title: "Check spill response materials are available",
      description: "Ensure spill kits or cleaning materials are accessible for quick response.",
      category: "housekeeping",
      frequency: "daily",
      evidenceRequired: false,
      notesHint: "Check spill kit contents if applicable",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/slips/",
      sortOrder: 3,
    },
    {
      title: "Check first aid supplies",
      description: "Verify first aid kit is stocked and accessible to staff.",
      category: "first-aid",
      frequency: "monthly",
      evidenceRequired: true,
      notesHint: "Check contents and expiry dates",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/firstaid/legislation.htm",
      sortOrder: 4,
    },
    {
      title: "Check visible electrical hazards",
      description: "Look for exposed wires, damaged sockets, or overloaded extension leads in public areas.",
      category: "equipment",
      frequency: "weekly",
      evidenceRequired: false,
      notesHint: "Note any hazards and actions taken",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/electricity/",
      sortOrder: 5,
    },
    {
      title: "Review incidents and hazards log",
      description: "Review incident, accident, and hazard reports from the past week.",
      category: "record-review",
      frequency: "weekly",
      evidenceRequired: false,
      notesHint: "Check for any follow-up actions needed",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/riddor/reporting.htm",
      sortOrder: 6,
    },
    {
      title: "Check fire exits remain clear",
      description: "Verify all fire exit doors are unobstructed and open correctly.",
      category: "fire-safety",
      frequency: "weekly",
      evidenceRequired: true,
      notesHint: "Check external escape routes too",
      sourceLabel: "GOV.UK",
      sourceUrl: "https://www.gov.uk/workplace-fire-safety-your-responsibilities",
      sortOrder: 7,
    },
    {
      title: "Test public address / warning system",
      description: "Verify PA system or fire alarm warning is audible throughout the premises.",
      category: "fire-safety",
      frequency: "monthly",
      evidenceRequired: false,
      notesHint: "Note any areas where alarm is hard to hear",
      sourceLabel: "GOV.UK",
      sourceUrl: "https://www.gov.uk/workplace-fire-safety-your-responsibilities",
      sortOrder: 8,
    },
  ],
}
