import type { TemplateItem } from "./types"

export const salonTemplate = {
  name: "Salon / Clinic",
  slug: "salon-clinic",
  sector: "salon",
  items: [
    {
      title: "Check floors are dry and safe",
      description: "Ensure all floor surfaces in treatment and reception areas are dry and slip-free.",
      category: "slips-trips",
      frequency: "daily",
      evidenceRequired: false,
      notesHint: "Note any wet areas or slip hazards",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/slips/",
      sortOrder: 1,
    },
    {
      title: "Check treatment areas are clean and sanitised",
      description: "Ensure all treatment areas, chairs, and surfaces are cleaned between clients.",
      category: "hygiene",
      frequency: "daily",
      evidenceRequired: true,
      notesHint: "Cleaning product used and areas cleaned",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/healthservices/beauty.htm",
      sortOrder: 2,
    },
    {
      title: "Check sharps / waste disposal process",
      description: "Verify sharps bins and clinical waste are stored and labelled correctly.",
      category: "waste",
      frequency: "weekly",
      evidenceRequired: true,
      notesHint: "Check bin fill levels and labelling",
      sourceLabel: "GOV.UK",
      sourceUrl: "https://www.gov.uk/clinical-waste-management",
      sortOrder: 3,
    },
    {
      title: "Check first aid supplies",
      description: "Verify first aid kit is stocked and accessible to staff.",
      category: "first-aid",
      frequency: "monthly",
      evidenceRequired: true,
      notesHint: "Check contents and expiry dates",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/firstaid/legislation.htm",
      sortOrder: 4,
    },
    {
      title: "Check electrical equipment visual condition",
      description: "Visually inspect all salon equipment for damaged cables, plugs, or casings.",
      category: "equipment",
      frequency: "monthly",
      evidenceRequired: false,
      notesHint: "Itemise any equipment needing repair",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/electricity/faq-portable-appliance-testing.htm",
      sortOrder: 5,
    },
    {
      title: "Review cleaning and incident log",
      description: "Review cleaning records and any incident entries from the past month.",
      category: "record-review",
      frequency: "monthly",
      evidenceRequired: false,
      notesHint: "Note any recurring issues",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/healthservices/beauty.htm",
      sortOrder: 6,
    },
    {
      title: "Check ventilation and air quality",
      description: "Ensure ventilation systems are working and treatment areas have adequate airflow.",
      category: "housekeeping",
      frequency: "weekly",
      evidenceRequired: false,
      notesHint: "Check extractor fans and windows",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/ventilation/",
      sortOrder: 7,
    },
  ],
}
