import type { TemplateItem } from "./types"

export const workshopTemplate = {
  name: "Workshop / Trades",
  slug: "workshop-trades",
  sector: "workshop",
  items: [
    {
      title: "Check access routes are clear",
      description: "Ensure all walkways, aisles, and emergency exits are free from materials and equipment.",
      category: "housekeeping",
      frequency: "daily",
      evidenceRequired: true,
      notesHint: "Note any blocked routes cleared",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/toolkit/workshops/checklist.htm",
      sortOrder: 1,
    },
    {
      title: "Check portable tools for visible damage",
      description: "Visually inspect portable power tools for damaged cables, plugs, or casings before use.",
      category: "equipment",
      frequency: "daily",
      evidenceRequired: false,
      notesHint: "Tag and remove any damaged tools",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/electricity/faq-portable-appliance-testing.htm",
      sortOrder: 2,
    },
    {
      title: "Check PPE availability and condition",
      description: "Verify required PPE is available, clean, and in good condition for all staff.",
      category: "ppe",
      frequency: "weekly",
      evidenceRequired: true,
      notesHint: "Check gloves, goggles, ear protection, masks",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/toolkit/ppe/checklist.htm",
      sortOrder: 3,
    },
    {
      title: "Check hazardous substance storage",
      description: "Ensure chemicals, solvents, and hazardous materials are stored correctly and labelled.",
      category: "hazardous",
      frequency: "weekly",
      evidenceRequired: true,
      notesHint: "Check COSHH assessments are current",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/coshh/",
      sortOrder: 4,
    },
    {
      title: "Check first aid kit",
      description: "Verify first aid kit is stocked and accessible.",
      category: "first-aid",
      frequency: "monthly",
      evidenceRequired: true,
      notesHint: "Check contents and expiry dates",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/firstaid/legislation.htm",
      sortOrder: 5,
    },
    {
      title: "Review incidents and near misses",
      description: "Review incident and near-miss records from the past month.",
      category: "record-review",
      frequency: "monthly",
      evidenceRequired: false,
      notesHint: "Note any patterns or follow-up actions",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/riddor/reporting.htm",
      sortOrder: 6,
    },
    {
      title: "Check dust extraction and ventilation",
      description: "Ensure dust extraction systems and ventilation are functioning correctly.",
      category: "housekeeping",
      frequency: "weekly",
      evidenceRequired: false,
      notesHint: "Check filters and airflow",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/woodworking/dust.htm",
      sortOrder: 7,
    },
    {
      title: "Inspect work at height equipment",
      description: "Check ladders, steps, and access platforms for damage or defects.",
      category: "equipment",
      frequency: "monthly",
      evidenceRequired: true,
      notesHint: "Tag any defective equipment out of use",
      sourceLabel: "HSE",
      sourceUrl: "https://www.hse.gov.uk/work-at-height/",
      sortOrder: 8,
    },
  ],
}
